# Generated by Django 6.0.1 on 2026-01-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomera',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='nomera',
            old_name='name',
            new_name='user_name',
        ),
    ]
