# Generated by Django 6.0.1 on 2026-01-20 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_rename_text_nomera_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
