# Generated by Django 6.0.1 on 2026-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0003_nomera_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomera',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
