# Generated by Django 6.0.1 on 2026-01-20 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_alter_nomera_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomera',
            name='created_at',
        ),
        migrations.AddField(
            model_name='nomera',
            name='ccreated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
