# Generated by Django 6.0.1 on 2026-01-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0005_remove_nomera_created_at_nomera_ccreated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomera',
            name='ccreated_at',
        ),
    ]
